//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CfdiSharpTest.Edicom {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com")]
    public partial class CFDiException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codField;
        
        private string textField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int cod {
            get {
                return this.codField;
            }
            set {
                this.codField = value;
                this.RaisePropertyChanged("cod");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", ConfigurationName="Edicom.CFDi")]
    public interface CFDi {
        
        // CODEGEN: El parámetro 'file' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUUIDReturn")]
        CfdiSharpTest.Edicom.getUUIDResponse getUUID(CfdiSharpTest.Edicom.getUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getUUIDResponse> getUUIDAsync(CfdiSharpTest.Edicom.getUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="changePasswordReturn")]
        bool changePassword(string user, string password, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="changePasswordReturn")]
        System.Threading.Tasks.Task<bool> changePasswordAsync(string user, string password, string newPassword);
        
        // CODEGEN: El parámetro 'getTimbreCfdiRetencionesTestReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTimbreCfdiRetencionesTestReturn")]
        CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestResponse getTimbreCfdiRetencionesTest(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestResponse> getTimbreCfdiRetencionesTestAsync(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest request);
        
        // CODEGEN: El parámetro 'getCfdiReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCfdiReturn")]
        CfdiSharpTest.Edicom.getCfdiResponse getCfdi(CfdiSharpTest.Edicom.getCfdiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiResponse> getCfdiAsync(CfdiSharpTest.Edicom.getCfdiRequest request);
        
        // CODEGEN: El parámetro 'getTimbreCfdiTestReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTimbreCfdiTestReturn")]
        CfdiSharpTest.Edicom.getTimbreCfdiTestResponse getTimbreCfdiTest(CfdiSharpTest.Edicom.getTimbreCfdiTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiTestResponse> getTimbreCfdiTestAsync(CfdiSharpTest.Edicom.getTimbreCfdiTestRequest request);
        
        // CODEGEN: El parámetro 'uuid' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelaCFDiRetencionesReturn")]
        CfdiSharpTest.Edicom.cancelaCFDiRetencionesResponse cancelaCFDiRetenciones(CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiRetencionesResponse> cancelaCFDiRetencionesAsync(CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest request);
        
        // CODEGEN: El parámetro 'getCfdiRetencionesTestReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCfdiRetencionesTestReturn")]
        CfdiSharpTest.Edicom.getCfdiRetencionesTestResponse getCfdiRetencionesTest(CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiRetencionesTestResponse> getCfdiRetencionesTestAsync(CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest request);
        
        // CODEGEN: El parámetro 'sign' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelaCFDiRetencionesSignedReturn")]
        CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedResponse cancelaCFDiRetencionesSigned(CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedResponse> cancelaCFDiRetencionesSignedAsync(CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest request);
        
        // CODEGEN: El parámetro 'exportCfdiReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="exportCfdiReturn")]
        CfdiSharpTest.Edicom.exportCfdiResponse exportCfdi(CfdiSharpTest.Edicom.exportCfdiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.exportCfdiResponse> exportCfdiAsync(CfdiSharpTest.Edicom.exportCfdiRequest request);
        
        // CODEGEN: El parámetro 'file' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getUUIDTestReturn")]
        CfdiSharpTest.Edicom.getUUIDTestResponse getUUIDTest(CfdiSharpTest.Edicom.getUUIDTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getUUIDTestResponse> getUUIDTestAsync(CfdiSharpTest.Edicom.getUUIDTestRequest request);
        
        // CODEGEN: El parámetro 'getTimbreCfdiReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTimbreCfdiReturn")]
        CfdiSharpTest.Edicom.getTimbreCfdiResponse getTimbreCfdi(CfdiSharpTest.Edicom.getTimbreCfdiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiResponse> getTimbreCfdiAsync(CfdiSharpTest.Edicom.getTimbreCfdiRequest request);
        
        // CODEGEN: El parámetro 'getCfdiTestReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCfdiTestReturn")]
        CfdiSharpTest.Edicom.getCfdiTestResponse getCfdiTest(CfdiSharpTest.Edicom.getCfdiTestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiTestResponse> getCfdiTestAsync(CfdiSharpTest.Edicom.getCfdiTestRequest request);
        
        // CODEGEN: El parámetro 'uuid' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelaCFDiReturn")]
        CfdiSharpTest.Edicom.cancelaCFDiResponse cancelaCFDi(CfdiSharpTest.Edicom.cancelaCFDiRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiResponse> cancelaCFDiAsync(CfdiSharpTest.Edicom.cancelaCFDiRequest request);
        
        // CODEGEN: El parámetro 'getTimbreCfdiRetencionesReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getTimbreCfdiRetencionesReturn")]
        CfdiSharpTest.Edicom.getTimbreCfdiRetencionesResponse getTimbreCfdiRetenciones(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiRetencionesResponse> getTimbreCfdiRetencionesAsync(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest request);
        
        // CODEGEN: El parámetro 'sign' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cancelaCFDiSignedReturn")]
        CfdiSharpTest.Edicom.cancelaCFDiSignedResponse cancelaCFDiSigned(CfdiSharpTest.Edicom.cancelaCFDiSignedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiSignedResponse> cancelaCFDiSignedAsync(CfdiSharpTest.Edicom.cancelaCFDiSignedRequest request);
        
        // CODEGEN: El parámetro 'getCfdiRetencionesReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCfdiRetencionesReturn")]
        CfdiSharpTest.Edicom.getCfdiRetencionesResponse getCfdiRetenciones(CfdiSharpTest.Edicom.getCfdiRetencionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiRetencionesResponse> getCfdiRetencionesAsync(CfdiSharpTest.Edicom.getCfdiRetencionesRequest request);
        
        // CODEGEN: El parámetro 'getCfdiFromUUIDReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCfdiFromUUIDReturn")]
        CfdiSharpTest.Edicom.getCfdiFromUUIDResponse getCfdiFromUUID(CfdiSharpTest.Edicom.getCfdiFromUUIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiFromUUIDResponse> getCfdiFromUUIDAsync(CfdiSharpTest.Edicom.getCfdiFromUUIDRequest request);
        
        // CODEGEN: El parámetro 'getCfdiAckReturn' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CfdiSharpTest.Edicom.CFDiException), Action="", Name="fault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getCfdiAckReturn")]
        CfdiSharpTest.Edicom.getCfdiAckResponse getCfdiAck(CfdiSharpTest.Edicom.getCfdiAckRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiAckResponse> getCfdiAckAsync(CfdiSharpTest.Edicom.getCfdiAckRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUID", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getUUIDRequest() {
        }
        
        public getUUIDRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUIDResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string getUUIDReturn;
        
        public getUUIDResponse() {
        }
        
        public getUUIDResponse(string getUUIDReturn) {
            this.getUUIDReturn = getUUIDReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetencionesTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiRetencionesTestRequest() {
        }
        
        public getTimbreCfdiRetencionesTestRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetencionesTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiRetencionesTestReturn;
        
        public getTimbreCfdiRetencionesTestResponse() {
        }
        
        public getTimbreCfdiRetencionesTestResponse(byte[] getTimbreCfdiRetencionesTestReturn) {
            this.getTimbreCfdiRetencionesTestReturn = getTimbreCfdiRetencionesTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiRequest() {
        }
        
        public getCfdiRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiReturn;
        
        public getCfdiResponse() {
        }
        
        public getCfdiResponse(byte[] getCfdiReturn) {
            this.getCfdiReturn = getCfdiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiTestRequest() {
        }
        
        public getTimbreCfdiTestRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiTestReturn;
        
        public getTimbreCfdiTestResponse() {
        }
        
        public getTimbreCfdiTestResponse(byte[] getTimbreCfdiTestReturn) {
            this.getTimbreCfdiTestReturn = getTimbreCfdiTestReturn;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com")]
    public partial class CancelaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ackField;
        
        private string textField;
        
        private string[] uuidsField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ack {
            get {
                return this.ackField;
            }
            set {
                this.ackField = value;
                this.RaisePropertyChanged("ack");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public string[] uuids {
            get {
                return this.uuidsField;
            }
            set {
                this.uuidsField = value;
                this.RaisePropertyChanged("uuids");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetenciones", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pfx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=5)]
        public string pfxPassword;
        
        public cancelaCFDiRetencionesRequest() {
        }
        
        public cancelaCFDiRetencionesRequest(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword) {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.uuid = uuid;
            this.pfx = pfx;
            this.pfxPassword = pfxPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetencionesResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiRetencionesReturn;
        
        public cancelaCFDiRetencionesResponse() {
        }
        
        public cancelaCFDiRetencionesResponse(CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiRetencionesReturn) {
            this.cancelaCFDiRetencionesReturn = cancelaCFDiRetencionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetencionesTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiRetencionesTestRequest() {
        }
        
        public getCfdiRetencionesTestRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetencionesTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiRetencionesTestReturn;
        
        public getCfdiRetencionesTestResponse() {
        }
        
        public getCfdiRetencionesTestResponse(byte[] getCfdiRetencionesTestReturn) {
            this.getCfdiRetencionesTestReturn = getCfdiRetencionesTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetencionesSigned", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesSignedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sign;
        
        public cancelaCFDiRetencionesSignedRequest() {
        }
        
        public cancelaCFDiRetencionesSignedRequest(string user, string password, byte[] sign) {
            this.user = user;
            this.password = password;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiRetencionesSignedResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRetencionesSignedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiRetencionesSignedReturn;
        
        public cancelaCFDiRetencionesSignedResponse() {
        }
        
        public cancelaCFDiRetencionesSignedResponse(CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiRetencionesSignedReturn) {
            this.cancelaCFDiRetencionesSignedReturn = cancelaCFDiRetencionesSignedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCfdi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class exportCfdiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        public System.DateTime iniDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        public System.DateTime endDate;
        
        public exportCfdiRequest() {
        }
        
        public exportCfdiRequest(string user, string password, string rfc, System.DateTime iniDate, System.DateTime endDate) {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.iniDate = iniDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportCfdiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class exportCfdiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] exportCfdiReturn;
        
        public exportCfdiResponse() {
        }
        
        public exportCfdiResponse(byte[] exportCfdiReturn) {
            this.exportCfdiReturn = exportCfdiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUIDTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getUUIDTestRequest() {
        }
        
        public getUUIDTestRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUUIDTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getUUIDTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string getUUIDTestReturn;
        
        public getUUIDTestResponse() {
        }
        
        public getUUIDTestResponse(string getUUIDTestReturn) {
            this.getUUIDTestReturn = getUUIDTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiRequest() {
        }
        
        public getTimbreCfdiRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiReturn;
        
        public getTimbreCfdiResponse() {
        }
        
        public getTimbreCfdiResponse(byte[] getTimbreCfdiReturn) {
            this.getTimbreCfdiReturn = getTimbreCfdiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiTest", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiTestRequest() {
        }
        
        public getCfdiTestRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiTestResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiTestReturn;
        
        public getCfdiTestResponse() {
        }
        
        public getCfdiTestResponse(byte[] getCfdiTestReturn) {
            this.getCfdiTestReturn = getCfdiTestReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDi", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] pfx;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=5)]
        public string pfxPassword;
        
        public cancelaCFDiRequest() {
        }
        
        public cancelaCFDiRequest(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword) {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.uuid = uuid;
            this.pfx = pfx;
            this.pfxPassword = pfxPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiReturn;
        
        public cancelaCFDiResponse() {
        }
        
        public cancelaCFDiResponse(CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiReturn) {
            this.cancelaCFDiReturn = cancelaCFDiReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetenciones", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getTimbreCfdiRetencionesRequest() {
        }
        
        public getTimbreCfdiRetencionesRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTimbreCfdiRetencionesResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getTimbreCfdiRetencionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getTimbreCfdiRetencionesReturn;
        
        public getTimbreCfdiRetencionesResponse() {
        }
        
        public getTimbreCfdiRetencionesResponse(byte[] getTimbreCfdiRetencionesReturn) {
            this.getTimbreCfdiRetencionesReturn = getTimbreCfdiRetencionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiSigned", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiSignedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] sign;
        
        public cancelaCFDiSignedRequest() {
        }
        
        public cancelaCFDiSignedRequest(string user, string password, byte[] sign) {
            this.user = user;
            this.password = password;
            this.sign = sign;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelaCFDiSignedResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class cancelaCFDiSignedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiSignedReturn;
        
        public cancelaCFDiSignedResponse() {
        }
        
        public cancelaCFDiSignedResponse(CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiSignedReturn) {
            this.cancelaCFDiSignedReturn = cancelaCFDiSignedReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetenciones", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        public getCfdiRetencionesRequest() {
        }
        
        public getCfdiRetencionesRequest(string user, string password, byte[] file) {
            this.user = user;
            this.password = password;
            this.file = file;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiRetencionesResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiRetencionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiRetencionesReturn;
        
        public getCfdiRetencionesResponse() {
        }
        
        public getCfdiRetencionesResponse(byte[] getCfdiRetencionesReturn) {
            this.getCfdiRetencionesReturn = getCfdiRetencionesReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiFromUUID", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiFromUUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        public string rfc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        public getCfdiFromUUIDRequest() {
        }
        
        public getCfdiFromUUIDRequest(string user, string password, string rfc, string[] uuid) {
            this.user = user;
            this.password = password;
            this.rfc = rfc;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiFromUUIDResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiFromUUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiFromUUIDReturn;
        
        public getCfdiFromUUIDResponse() {
        }
        
        public getCfdiFromUUIDResponse(byte[] getCfdiFromUUIDReturn) {
            this.getCfdiFromUUIDReturn = getCfdiFromUUIDReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiAck", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiAckRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("uuid")]
        public string[] uuid;
        
        public getCfdiAckRequest() {
        }
        
        public getCfdiAckRequest(string user, string password, string[] uuid) {
            this.user = user;
            this.password = password;
            this.uuid = uuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCfdiAckResponse", WrapperNamespace="http://cfdi.service.ediwinws.edicom.com", IsWrapped=true)]
    public partial class getCfdiAckResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cfdi.service.ediwinws.edicom.com", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getCfdiAckReturn;
        
        public getCfdiAckResponse() {
        }
        
        public getCfdiAckResponse(byte[] getCfdiAckReturn) {
            this.getCfdiAckReturn = getCfdiAckReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CFDiChannel : CfdiSharpTest.Edicom.CFDi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFDiClient : System.ServiceModel.ClientBase<CfdiSharpTest.Edicom.CFDi>, CfdiSharpTest.Edicom.CFDi {
        
        public CFDiClient() {
        }
        
        public CFDiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFDiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFDiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFDiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getUUIDResponse CfdiSharpTest.Edicom.CFDi.getUUID(CfdiSharpTest.Edicom.getUUIDRequest request) {
            return base.Channel.getUUID(request);
        }
        
        public string getUUID(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getUUIDRequest inValue = new CfdiSharpTest.Edicom.getUUIDRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getUUIDResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getUUID(inValue);
            return retVal.getUUIDReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getUUIDResponse> CfdiSharpTest.Edicom.CFDi.getUUIDAsync(CfdiSharpTest.Edicom.getUUIDRequest request) {
            return base.Channel.getUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getUUIDResponse> getUUIDAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getUUIDRequest inValue = new CfdiSharpTest.Edicom.getUUIDRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getUUIDAsync(inValue);
        }
        
        public bool changePassword(string user, string password, string newPassword) {
            return base.Channel.changePassword(user, password, newPassword);
        }
        
        public System.Threading.Tasks.Task<bool> changePasswordAsync(string user, string password, string newPassword) {
            return base.Channel.changePasswordAsync(user, password, newPassword);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestResponse CfdiSharpTest.Edicom.CFDi.getTimbreCfdiRetencionesTest(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest request) {
            return base.Channel.getTimbreCfdiRetencionesTest(request);
        }
        
        public byte[] getTimbreCfdiRetencionesTest(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdiRetencionesTest(inValue);
            return retVal.getTimbreCfdiRetencionesTestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestResponse> CfdiSharpTest.Edicom.CFDi.getTimbreCfdiRetencionesTestAsync(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest request) {
            return base.Channel.getTimbreCfdiRetencionesTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestResponse> getTimbreCfdiRetencionesTestAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiRetencionesTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdiRetencionesTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getCfdiResponse CfdiSharpTest.Edicom.CFDi.getCfdi(CfdiSharpTest.Edicom.getCfdiRequest request) {
            return base.Channel.getCfdi(request);
        }
        
        public byte[] getCfdi(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiRequest inValue = new CfdiSharpTest.Edicom.getCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getCfdiResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdi(inValue);
            return retVal.getCfdiReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiResponse> CfdiSharpTest.Edicom.CFDi.getCfdiAsync(CfdiSharpTest.Edicom.getCfdiRequest request) {
            return base.Channel.getCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiResponse> getCfdiAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiRequest inValue = new CfdiSharpTest.Edicom.getCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getTimbreCfdiTestResponse CfdiSharpTest.Edicom.CFDi.getTimbreCfdiTest(CfdiSharpTest.Edicom.getTimbreCfdiTestRequest request) {
            return base.Channel.getTimbreCfdiTest(request);
        }
        
        public byte[] getTimbreCfdiTest(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiTestRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getTimbreCfdiTestResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdiTest(inValue);
            return retVal.getTimbreCfdiTestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiTestResponse> CfdiSharpTest.Edicom.CFDi.getTimbreCfdiTestAsync(CfdiSharpTest.Edicom.getTimbreCfdiTestRequest request) {
            return base.Channel.getTimbreCfdiTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiTestResponse> getTimbreCfdiTestAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiTestRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdiTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.cancelaCFDiRetencionesResponse CfdiSharpTest.Edicom.CFDi.cancelaCFDiRetenciones(CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest request) {
            return base.Channel.cancelaCFDiRetenciones(request);
        }
        
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiRetenciones(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword) {
            CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            inValue.pfx = pfx;
            inValue.pfxPassword = pfxPassword;
            CfdiSharpTest.Edicom.cancelaCFDiRetencionesResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDiRetenciones(inValue);
            return retVal.cancelaCFDiRetencionesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiRetencionesResponse> CfdiSharpTest.Edicom.CFDi.cancelaCFDiRetencionesAsync(CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest request) {
            return base.Channel.cancelaCFDiRetencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiRetencionesResponse> cancelaCFDiRetencionesAsync(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword) {
            CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            inValue.pfx = pfx;
            inValue.pfxPassword = pfxPassword;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDiRetencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getCfdiRetencionesTestResponse CfdiSharpTest.Edicom.CFDi.getCfdiRetencionesTest(CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest request) {
            return base.Channel.getCfdiRetencionesTest(request);
        }
        
        public byte[] getCfdiRetencionesTest(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest inValue = new CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getCfdiRetencionesTestResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiRetencionesTest(inValue);
            return retVal.getCfdiRetencionesTestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiRetencionesTestResponse> CfdiSharpTest.Edicom.CFDi.getCfdiRetencionesTestAsync(CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest request) {
            return base.Channel.getCfdiRetencionesTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiRetencionesTestResponse> getCfdiRetencionesTestAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest inValue = new CfdiSharpTest.Edicom.getCfdiRetencionesTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiRetencionesTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedResponse CfdiSharpTest.Edicom.CFDi.cancelaCFDiRetencionesSigned(CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest request) {
            return base.Channel.cancelaCFDiRetencionesSigned(request);
        }
        
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiRetencionesSigned(string user, string password, byte[] sign) {
            CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.sign = sign;
            CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDiRetencionesSigned(inValue);
            return retVal.cancelaCFDiRetencionesSignedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedResponse> CfdiSharpTest.Edicom.CFDi.cancelaCFDiRetencionesSignedAsync(CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest request) {
            return base.Channel.cancelaCFDiRetencionesSignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedResponse> cancelaCFDiRetencionesSignedAsync(string user, string password, byte[] sign) {
            CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiRetencionesSignedRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.sign = sign;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDiRetencionesSignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.exportCfdiResponse CfdiSharpTest.Edicom.CFDi.exportCfdi(CfdiSharpTest.Edicom.exportCfdiRequest request) {
            return base.Channel.exportCfdi(request);
        }
        
        public byte[] exportCfdi(string user, string password, string rfc, System.DateTime iniDate, System.DateTime endDate) {
            CfdiSharpTest.Edicom.exportCfdiRequest inValue = new CfdiSharpTest.Edicom.exportCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.iniDate = iniDate;
            inValue.endDate = endDate;
            CfdiSharpTest.Edicom.exportCfdiResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).exportCfdi(inValue);
            return retVal.exportCfdiReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.exportCfdiResponse> CfdiSharpTest.Edicom.CFDi.exportCfdiAsync(CfdiSharpTest.Edicom.exportCfdiRequest request) {
            return base.Channel.exportCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.exportCfdiResponse> exportCfdiAsync(string user, string password, string rfc, System.DateTime iniDate, System.DateTime endDate) {
            CfdiSharpTest.Edicom.exportCfdiRequest inValue = new CfdiSharpTest.Edicom.exportCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.iniDate = iniDate;
            inValue.endDate = endDate;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).exportCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getUUIDTestResponse CfdiSharpTest.Edicom.CFDi.getUUIDTest(CfdiSharpTest.Edicom.getUUIDTestRequest request) {
            return base.Channel.getUUIDTest(request);
        }
        
        public string getUUIDTest(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getUUIDTestRequest inValue = new CfdiSharpTest.Edicom.getUUIDTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getUUIDTestResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getUUIDTest(inValue);
            return retVal.getUUIDTestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getUUIDTestResponse> CfdiSharpTest.Edicom.CFDi.getUUIDTestAsync(CfdiSharpTest.Edicom.getUUIDTestRequest request) {
            return base.Channel.getUUIDTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getUUIDTestResponse> getUUIDTestAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getUUIDTestRequest inValue = new CfdiSharpTest.Edicom.getUUIDTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getUUIDTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getTimbreCfdiResponse CfdiSharpTest.Edicom.CFDi.getTimbreCfdi(CfdiSharpTest.Edicom.getTimbreCfdiRequest request) {
            return base.Channel.getTimbreCfdi(request);
        }
        
        public byte[] getTimbreCfdi(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getTimbreCfdiResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdi(inValue);
            return retVal.getTimbreCfdiReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiResponse> CfdiSharpTest.Edicom.CFDi.getTimbreCfdiAsync(CfdiSharpTest.Edicom.getTimbreCfdiRequest request) {
            return base.Channel.getTimbreCfdiAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiResponse> getTimbreCfdiAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getCfdiTestResponse CfdiSharpTest.Edicom.CFDi.getCfdiTest(CfdiSharpTest.Edicom.getCfdiTestRequest request) {
            return base.Channel.getCfdiTest(request);
        }
        
        public byte[] getCfdiTest(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiTestRequest inValue = new CfdiSharpTest.Edicom.getCfdiTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getCfdiTestResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiTest(inValue);
            return retVal.getCfdiTestReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiTestResponse> CfdiSharpTest.Edicom.CFDi.getCfdiTestAsync(CfdiSharpTest.Edicom.getCfdiTestRequest request) {
            return base.Channel.getCfdiTestAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiTestResponse> getCfdiTestAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiTestRequest inValue = new CfdiSharpTest.Edicom.getCfdiTestRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiTestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.cancelaCFDiResponse CfdiSharpTest.Edicom.CFDi.cancelaCFDi(CfdiSharpTest.Edicom.cancelaCFDiRequest request) {
            return base.Channel.cancelaCFDi(request);
        }
        
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDi(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword) {
            CfdiSharpTest.Edicom.cancelaCFDiRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            inValue.pfx = pfx;
            inValue.pfxPassword = pfxPassword;
            CfdiSharpTest.Edicom.cancelaCFDiResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDi(inValue);
            return retVal.cancelaCFDiReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiResponse> CfdiSharpTest.Edicom.CFDi.cancelaCFDiAsync(CfdiSharpTest.Edicom.cancelaCFDiRequest request) {
            return base.Channel.cancelaCFDiAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiResponse> cancelaCFDiAsync(string user, string password, string rfc, string[] uuid, byte[] pfx, string pfxPassword) {
            CfdiSharpTest.Edicom.cancelaCFDiRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            inValue.pfx = pfx;
            inValue.pfxPassword = pfxPassword;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDiAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getTimbreCfdiRetencionesResponse CfdiSharpTest.Edicom.CFDi.getTimbreCfdiRetenciones(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest request) {
            return base.Channel.getTimbreCfdiRetenciones(request);
        }
        
        public byte[] getTimbreCfdiRetenciones(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getTimbreCfdiRetencionesResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdiRetenciones(inValue);
            return retVal.getTimbreCfdiRetencionesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiRetencionesResponse> CfdiSharpTest.Edicom.CFDi.getTimbreCfdiRetencionesAsync(CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest request) {
            return base.Channel.getTimbreCfdiRetencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getTimbreCfdiRetencionesResponse> getTimbreCfdiRetencionesAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest inValue = new CfdiSharpTest.Edicom.getTimbreCfdiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getTimbreCfdiRetencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.cancelaCFDiSignedResponse CfdiSharpTest.Edicom.CFDi.cancelaCFDiSigned(CfdiSharpTest.Edicom.cancelaCFDiSignedRequest request) {
            return base.Channel.cancelaCFDiSigned(request);
        }
        
        public CfdiSharpTest.Edicom.CancelaResponse cancelaCFDiSigned(string user, string password, byte[] sign) {
            CfdiSharpTest.Edicom.cancelaCFDiSignedRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiSignedRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.sign = sign;
            CfdiSharpTest.Edicom.cancelaCFDiSignedResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDiSigned(inValue);
            return retVal.cancelaCFDiSignedReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiSignedResponse> CfdiSharpTest.Edicom.CFDi.cancelaCFDiSignedAsync(CfdiSharpTest.Edicom.cancelaCFDiSignedRequest request) {
            return base.Channel.cancelaCFDiSignedAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.cancelaCFDiSignedResponse> cancelaCFDiSignedAsync(string user, string password, byte[] sign) {
            CfdiSharpTest.Edicom.cancelaCFDiSignedRequest inValue = new CfdiSharpTest.Edicom.cancelaCFDiSignedRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.sign = sign;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).cancelaCFDiSignedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getCfdiRetencionesResponse CfdiSharpTest.Edicom.CFDi.getCfdiRetenciones(CfdiSharpTest.Edicom.getCfdiRetencionesRequest request) {
            return base.Channel.getCfdiRetenciones(request);
        }
        
        public byte[] getCfdiRetenciones(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiRetencionesRequest inValue = new CfdiSharpTest.Edicom.getCfdiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            CfdiSharpTest.Edicom.getCfdiRetencionesResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiRetenciones(inValue);
            return retVal.getCfdiRetencionesReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiRetencionesResponse> CfdiSharpTest.Edicom.CFDi.getCfdiRetencionesAsync(CfdiSharpTest.Edicom.getCfdiRetencionesRequest request) {
            return base.Channel.getCfdiRetencionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiRetencionesResponse> getCfdiRetencionesAsync(string user, string password, byte[] file) {
            CfdiSharpTest.Edicom.getCfdiRetencionesRequest inValue = new CfdiSharpTest.Edicom.getCfdiRetencionesRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.file = file;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiRetencionesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getCfdiFromUUIDResponse CfdiSharpTest.Edicom.CFDi.getCfdiFromUUID(CfdiSharpTest.Edicom.getCfdiFromUUIDRequest request) {
            return base.Channel.getCfdiFromUUID(request);
        }
        
        public byte[] getCfdiFromUUID(string user, string password, string rfc, string[] uuid) {
            CfdiSharpTest.Edicom.getCfdiFromUUIDRequest inValue = new CfdiSharpTest.Edicom.getCfdiFromUUIDRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            CfdiSharpTest.Edicom.getCfdiFromUUIDResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiFromUUID(inValue);
            return retVal.getCfdiFromUUIDReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiFromUUIDResponse> CfdiSharpTest.Edicom.CFDi.getCfdiFromUUIDAsync(CfdiSharpTest.Edicom.getCfdiFromUUIDRequest request) {
            return base.Channel.getCfdiFromUUIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiFromUUIDResponse> getCfdiFromUUIDAsync(string user, string password, string rfc, string[] uuid) {
            CfdiSharpTest.Edicom.getCfdiFromUUIDRequest inValue = new CfdiSharpTest.Edicom.getCfdiFromUUIDRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.rfc = rfc;
            inValue.uuid = uuid;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiFromUUIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CfdiSharpTest.Edicom.getCfdiAckResponse CfdiSharpTest.Edicom.CFDi.getCfdiAck(CfdiSharpTest.Edicom.getCfdiAckRequest request) {
            return base.Channel.getCfdiAck(request);
        }
        
        public byte[] getCfdiAck(string user, string password, string[] uuid) {
            CfdiSharpTest.Edicom.getCfdiAckRequest inValue = new CfdiSharpTest.Edicom.getCfdiAckRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.uuid = uuid;
            CfdiSharpTest.Edicom.getCfdiAckResponse retVal = ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiAck(inValue);
            return retVal.getCfdiAckReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiAckResponse> CfdiSharpTest.Edicom.CFDi.getCfdiAckAsync(CfdiSharpTest.Edicom.getCfdiAckRequest request) {
            return base.Channel.getCfdiAckAsync(request);
        }
        
        public System.Threading.Tasks.Task<CfdiSharpTest.Edicom.getCfdiAckResponse> getCfdiAckAsync(string user, string password, string[] uuid) {
            CfdiSharpTest.Edicom.getCfdiAckRequest inValue = new CfdiSharpTest.Edicom.getCfdiAckRequest();
            inValue.user = user;
            inValue.password = password;
            inValue.uuid = uuid;
            return ((CfdiSharpTest.Edicom.CFDi)(this)).getCfdiAckAsync(inValue);
        }
    }
}
